"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_py.models.components import (
    dto_cancelsubscriptionrequest as components_dto_cancelsubscriptionrequest,
)
from flexprice_py.types import BaseModel
from flexprice_py.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class CancelSubscriptionRequestTypedDict(TypedDict):
    id: str
    r"""Subscription ID"""
    body: components_dto_cancelsubscriptionrequest.DtoCancelSubscriptionRequestTypedDict
    r"""Cancel Subscription Request"""


class CancelSubscriptionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Subscription ID"""

    body: Annotated[
        components_dto_cancelsubscriptionrequest.DtoCancelSubscriptionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Cancel Subscription Request"""
