"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_py.models.components import (
    dto_deletesubscriptionlineitemrequest as components_dto_deletesubscriptionlineitemrequest,
)
from flexprice_py.types import BaseModel
from flexprice_py.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class DeleteSubscriptionLineItemRequestTypedDict(TypedDict):
    id: str
    r"""Line Item ID"""
    body: components_dto_deletesubscriptionlineitemrequest.DtoDeleteSubscriptionLineItemRequestTypedDict
    r"""Delete Line Item Request"""


class DeleteSubscriptionLineItemRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Line Item ID"""

    body: Annotated[
        components_dto_deletesubscriptionlineitemrequest.DtoDeleteSubscriptionLineItemRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Delete Line Item Request"""
