"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_py.models.components import (
    dto_updatetaskstatusrequest as components_dto_updatetaskstatusrequest,
)
from flexprice_py.types import BaseModel
from flexprice_py.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateTaskStatusRequestTypedDict(TypedDict):
    id: str
    r"""Task ID"""
    body: components_dto_updatetaskstatusrequest.DtoUpdateTaskStatusRequestTypedDict
    r"""Status update"""


class UpdateTaskStatusRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Task ID"""

    body: Annotated[
        components_dto_updatetaskstatusrequest.DtoUpdateTaskStatusRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Status update"""
