"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_py.models.components import (
    dto_updateaddonrequest as components_dto_updateaddonrequest,
)
from flexprice_py.types import BaseModel
from flexprice_py.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateAddonRequestTypedDict(TypedDict):
    id: str
    r"""Addon ID"""
    body: components_dto_updateaddonrequest.DtoUpdateAddonRequestTypedDict
    r"""Update Addon Request"""


class UpdateAddonRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Addon ID"""

    body: Annotated[
        components_dto_updateaddonrequest.DtoUpdateAddonRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Update Addon Request"""
