"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from flexprice_sdk_test.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetEntitlementsEntityType(str, Enum):
    PLAN = "PLAN"
    SUBSCRIPTION = "SUBSCRIPTION"
    ADDON = "ADDON"


class FeatureType(str, Enum):
    METERED = "metered"
    BOOLEAN = "boolean"
    STATIC = "static"


class GetEntitlementsOrder(str, Enum):
    ASC = "asc"
    DESC = "desc"


class GetEntitlementsStatus(str, Enum):
    PUBLISHED = "published"
    DELETED = "deleted"
    ARCHIVED = "archived"


class GetEntitlementsRequestTypedDict(TypedDict):
    end_time: NotRequired[str]
    entity_ids: NotRequired[List[str]]
    entity_type: NotRequired[GetEntitlementsEntityType]
    expand: NotRequired[str]
    feature_ids: NotRequired[List[str]]
    feature_type: NotRequired[FeatureType]
    is_enabled: NotRequired[bool]
    limit: NotRequired[int]
    offset: NotRequired[int]
    order: NotRequired[GetEntitlementsOrder]
    plan_ids: NotRequired[List[str]]
    start_time: NotRequired[str]
    status: NotRequired[GetEntitlementsStatus]


class GetEntitlementsRequest(BaseModel):
    end_time: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    entity_ids: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None

    entity_type: Annotated[
        Optional[GetEntitlementsEntityType],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    expand: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    feature_ids: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None

    feature_type: Annotated[
        Optional[FeatureType],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    is_enabled: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    order: Annotated[
        Optional[GetEntitlementsOrder],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    plan_ids: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None

    start_time: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    status: Annotated[
        Optional[GetEntitlementsStatus],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "end_time",
                "entity_ids",
                "entity_type",
                "expand",
                "feature_ids",
                "feature_type",
                "is_enabled",
                "limit",
                "offset",
                "order",
                "plan_ids",
                "start_time",
                "status",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
