"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from flexprice_sdk_test.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetEntityIntegrationMappingsRequestTypedDict(TypedDict):
    entity_id: NotRequired[str]
    r"""Filter by FlexPrice entity ID"""
    entity_type: NotRequired[str]
    r"""Filter by entity type"""
    provider_type: NotRequired[str]
    r"""Filter by provider type"""
    provider_entity_id: NotRequired[str]
    r"""Filter by provider entity ID"""
    limit: NotRequired[int]
    r"""Number of results to return (default: 20, max: 100)"""
    offset: NotRequired[int]
    r"""Pagination offset (default: 0)"""


class GetEntityIntegrationMappingsRequest(BaseModel):
    entity_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by FlexPrice entity ID"""

    entity_type: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by entity type"""

    provider_type: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by provider type"""

    provider_entity_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by provider entity ID"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Number of results to return (default: 20, max: 100)"""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Pagination offset (default: 0)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "entity_id",
                "entity_type",
                "provider_type",
                "provider_entity_id",
                "limit",
                "offset",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
