"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from flexprice_sdk_test.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetTaxesRatesOrder(str, Enum):
    ASC = "asc"
    DESC = "desc"


class GetTaxesRatesScope(str, Enum):
    INTERNAL = "INTERNAL"
    EXTERNAL = "EXTERNAL"
    ONETIME = "ONETIME"


class GetTaxesRatesStatus(str, Enum):
    PUBLISHED = "published"
    DELETED = "deleted"
    ARCHIVED = "archived"


class GetTaxesRatesRequestTypedDict(TypedDict):
    end_time: NotRequired[str]
    expand: NotRequired[str]
    limit: NotRequired[int]
    offset: NotRequired[int]
    order: NotRequired[GetTaxesRatesOrder]
    scope: NotRequired[GetTaxesRatesScope]
    start_time: NotRequired[str]
    status: NotRequired[GetTaxesRatesStatus]
    taxrate_codes: NotRequired[List[str]]
    taxrate_ids: NotRequired[List[str]]


class GetTaxesRatesRequest(BaseModel):
    end_time: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    expand: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    order: Annotated[
        Optional[GetTaxesRatesOrder],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    scope: Annotated[
        Optional[GetTaxesRatesScope],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    start_time: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    status: Annotated[
        Optional[GetTaxesRatesStatus],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    taxrate_codes: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None

    taxrate_ids: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "end_time",
                "expand",
                "limit",
                "offset",
                "order",
                "scope",
                "start_time",
                "status",
                "taxrate_codes",
                "taxrate_ids",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
