"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_sdk_test.types import BaseModel
from flexprice_sdk_test.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetV1SubscriptionSchedulesIDRequestTypedDict(TypedDict):
    id: str
    r"""Schedule ID"""


class GetV1SubscriptionSchedulesIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Schedule ID"""
