"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_py.types import BaseModel
from flexprice_py.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetPriceByLookupKeyRequestTypedDict(TypedDict):
    lookup_key: str
    r"""Lookup key"""


class GetPriceByLookupKeyRequest(BaseModel):
    lookup_key: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Lookup key"""
