"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_pausesubscriptionrequest import (
    DtoPauseSubscriptionRequest,
    DtoPauseSubscriptionRequestTypedDict,
)
from flexprice_py.types import BaseModel
from flexprice_py.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class PauseSubscriptionRequestTypedDict(TypedDict):
    id: str
    r"""Subscription ID"""
    body: DtoPauseSubscriptionRequestTypedDict
    r"""Pause subscription request"""


class PauseSubscriptionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Subscription ID"""

    body: Annotated[
        DtoPauseSubscriptionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Pause subscription request"""
