"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_py.types import UnrecognizedStr
from typing import Literal, Union


TypesCreditGrantApplicationReason = Union[
    Literal[
        "first_time_recurring_credit_grant",
        "recurring_credit_grant",
        "onetime_credit_grant",
    ],
    UnrecognizedStr,
]
