"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_updateenvironmentrequest import (
    DtoUpdateEnvironmentRequest,
    DtoUpdateEnvironmentRequestTypedDict,
)
from flexprice_py.types import BaseModel
from flexprice_py.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateEnvironmentRequestTypedDict(TypedDict):
    id: str
    r"""Environment ID"""
    body: DtoUpdateEnvironmentRequestTypedDict
    r"""Environment"""


class UpdateEnvironmentRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Environment ID"""

    body: Annotated[
        DtoUpdateEnvironmentRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Environment"""
