"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_updatecostsheetrequest import (
    DtoUpdateCostsheetRequest,
    DtoUpdateCostsheetRequestTypedDict,
)
from flexprice_py.types import BaseModel
from flexprice_py.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateCostsheetRequestTypedDict(TypedDict):
    id: str
    r"""Costsheet ID"""
    body: DtoUpdateCostsheetRequestTypedDict
    r"""Costsheet configuration"""


class UpdateCostsheetRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Costsheet ID"""

    body: Annotated[
        DtoUpdateCostsheetRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Costsheet configuration"""
