"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_py.types import (
    BaseModel,
    dto_activatedraftsubscriptionrequest as types_dto_activatedraftsubscriptionrequest,
)
from flexprice_py.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ActivateSubscriptionRequestTypedDict(TypedDict):
    id: str
    r"""Subscription ID"""
    body: types_dto_activatedraftsubscriptionrequest.DtoActivateDraftSubscriptionRequestTypedDict
    r"""Activate Draft Subscription Request"""


class ActivateSubscriptionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Subscription ID"""

    body: Annotated[
        types_dto_activatedraftsubscriptionrequest.DtoActivateDraftSubscriptionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Activate Draft Subscription Request"""
