"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_py.types import (
    BaseModel,
    dto_cloneplanrequest as types_dto_cloneplanrequest,
)
from flexprice_py.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class PostPlansIDCloneRequestTypedDict(TypedDict):
    id: str
    r"""Source Plan ID"""
    body: types_dto_cloneplanrequest.DtoClonePlanRequestTypedDict
    r"""Clone configuration"""


class PostPlansIDCloneRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Source Plan ID"""

    body: Annotated[
        types_dto_cloneplanrequest.DtoClonePlanRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Clone configuration"""
