"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_py.types import (
    BaseModel,
    dto_updatesubscriptionrequest as types_dto_updatesubscriptionrequest,
)
from flexprice_py.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateSubscriptionRequestTypedDict(TypedDict):
    id: str
    r"""Subscription ID"""
    body: types_dto_updatesubscriptionrequest.DtoUpdateSubscriptionRequestTypedDict
    r"""Update Subscription Request"""


class UpdateSubscriptionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Subscription ID"""

    body: Annotated[
        types_dto_updatesubscriptionrequest.DtoUpdateSubscriptionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Update Subscription Request"""
