"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_py.types import (
    BaseModel,
    dto_updatescheduledtaskrequest as types_dto_updatescheduledtaskrequest,
)
from flexprice_py.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateScheduledTaskRequestTypedDict(TypedDict):
    id: str
    r"""Scheduled Task ID"""
    body: types_dto_updatescheduledtaskrequest.DtoUpdateScheduledTaskRequestTypedDict
    r"""Update request (enabled: true/false to pause/resume)"""


class UpdateScheduledTaskRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Scheduled Task ID"""

    body: Annotated[
        types_dto_updatescheduledtaskrequest.DtoUpdateScheduledTaskRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Update request (enabled: true/false to pause/resume)"""
