"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_py.types import (
    BaseModel,
    dto_updatepricerequest as types_dto_updatepricerequest,
)
from flexprice_py.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdatePriceRequestTypedDict(TypedDict):
    id: str
    r"""Price ID"""
    body: types_dto_updatepricerequest.DtoUpdatePriceRequestTypedDict
    r"""Price configuration"""


class UpdatePriceRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Price ID"""

    body: Annotated[
        types_dto_updatepricerequest.DtoUpdatePriceRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Price configuration"""
