"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_py.types import (
    BaseModel,
    dto_updatecouponrequest as types_dto_updatecouponrequest,
)
from flexprice_py.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateCouponRequestTypedDict(TypedDict):
    id: str
    r"""Coupon ID"""
    body: types_dto_updatecouponrequest.DtoUpdateCouponRequestTypedDict
    r"""Coupon update request"""


class UpdateCouponRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Coupon ID"""

    body: Annotated[
        types_dto_updatecouponrequest.DtoUpdateCouponRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Coupon update request"""
