"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_py.types import (
    BaseModel,
    dto_updatepriceunitrequest as types_dto_updatepriceunitrequest,
)
from flexprice_py.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdatePriceUnitRequestTypedDict(TypedDict):
    id: str
    r"""Price unit ID"""
    body: types_dto_updatepriceunitrequest.DtoUpdatePriceUnitRequestTypedDict
    r"""Price unit details to update"""


class UpdatePriceUnitRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Price unit ID"""

    body: Annotated[
        types_dto_updatepriceunitrequest.DtoUpdatePriceUnitRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Price unit details to update"""
