"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_py.types import (
    BaseModel,
    dto_updateentitlementrequest as types_dto_updateentitlementrequest,
)
from flexprice_py.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateEntitlementRequestTypedDict(TypedDict):
    id: str
    r"""Entitlement ID"""
    body: types_dto_updateentitlementrequest.DtoUpdateEntitlementRequestTypedDict
    r"""Entitlement configuration"""


class UpdateEntitlementRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Entitlement ID"""

    body: Annotated[
        types_dto_updateentitlementrequest.DtoUpdateEntitlementRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Entitlement configuration"""
