"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .alertthreshold import AlertThreshold, AlertThresholdTypedDict
from flexprice_py.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AlertSettingsTypedDict(TypedDict):
    alert_enabled: NotRequired[bool]
    critical: NotRequired[AlertThresholdTypedDict]
    info: NotRequired[AlertThresholdTypedDict]
    warning: NotRequired[AlertThresholdTypedDict]


class AlertSettings(BaseModel):
    alert_enabled: Optional[bool] = None

    critical: Optional[AlertThreshold] = None

    info: Optional[AlertThreshold] = None

    warning: Optional[AlertThreshold] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["alert_enabled", "critical", "info", "warning"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
