"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .alertsettings import AlertSettings, AlertSettingsTypedDict
from .dto_createmeterrequest import (
    DtoCreateMeterRequest,
    DtoCreateMeterRequestTypedDict,
)
from .featuretype import FeatureType
from flexprice_py.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class DtoCreateFeatureRequestTypedDict(TypedDict):
    name: str
    type: FeatureType
    alert_settings: NotRequired[AlertSettingsTypedDict]
    description: NotRequired[str]
    lookup_key: NotRequired[str]
    metadata: NotRequired[Dict[str, str]]
    meter: NotRequired[DtoCreateMeterRequestTypedDict]
    meter_id: NotRequired[str]
    unit_plural: NotRequired[str]
    unit_singular: NotRequired[str]


class DtoCreateFeatureRequest(BaseModel):
    name: str

    type: FeatureType

    alert_settings: Optional[AlertSettings] = None

    description: Optional[str] = None

    lookup_key: Optional[str] = None

    metadata: Optional[Dict[str, str]] = None

    meter: Optional[DtoCreateMeterRequest] = None

    meter_id: Optional[str] = None

    unit_plural: Optional[str] = None

    unit_singular: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "alert_settings",
                "description",
                "lookup_key",
                "metadata",
                "meter",
                "meter_id",
                "unit_plural",
                "unit_singular",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
