"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .types_status import TypesStatus
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class CreditnoteCreditNoteLineItemTypedDict(TypedDict):
    amount: NotRequired[str]
    created_at: NotRequired[str]
    created_by: NotRequired[str]
    credit_note_id: NotRequired[str]
    currency: NotRequired[str]
    display_name: NotRequired[str]
    environment_id: NotRequired[str]
    id: NotRequired[str]
    invoice_line_item_id: NotRequired[str]
    metadata: NotRequired[Dict[str, str]]
    status: NotRequired[TypesStatus]
    tenant_id: NotRequired[str]
    updated_at: NotRequired[str]
    updated_by: NotRequired[str]


class CreditnoteCreditNoteLineItem(BaseModel):
    amount: Optional[str] = None

    created_at: Optional[str] = None

    created_by: Optional[str] = None

    credit_note_id: Optional[str] = None

    currency: Optional[str] = None

    display_name: Optional[str] = None

    environment_id: Optional[str] = None

    id: Optional[str] = None

    invoice_line_item_id: Optional[str] = None

    metadata: Optional[Dict[str, str]] = None

    status: Optional[TypesStatus] = None

    tenant_id: Optional[str] = None

    updated_at: Optional[str] = None

    updated_by: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "amount",
                "created_at",
                "created_by",
                "credit_note_id",
                "currency",
                "display_name",
                "environment_id",
                "id",
                "invoice_line_item_id",
                "metadata",
                "status",
                "tenant_id",
                "updated_at",
                "updated_by",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
