"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_secretresponse import DtoSecretResponse, DtoSecretResponseTypedDict
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DtoCreateAPIKeyResponseTypedDict(TypedDict):
    api_key: NotRequired[str]
    secret: NotRequired[DtoSecretResponseTypedDict]


class DtoCreateAPIKeyResponse(BaseModel):
    api_key: Optional[str] = None

    secret: Optional[DtoSecretResponse] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["api_key", "secret"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
