"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_eventcountpoint import DtoEventCountPoint, DtoEventCountPointTypedDict
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class DtoGetMonitoringDataResponseTypedDict(TypedDict):
    consumption_lag: NotRequired[int]
    points: NotRequired[List[DtoEventCountPointTypedDict]]
    post_processing_lag: NotRequired[int]
    total_count: NotRequired[int]


class DtoGetMonitoringDataResponse(BaseModel):
    consumption_lag: Optional[int] = None

    points: Optional[List[DtoEventCountPoint]] = None

    post_processing_lag: Optional[int] = None

    total_count: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["consumption_lag", "points", "post_processing_lag", "total_count"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
