"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .types_secrettype import TypesSecretType
from flexprice_sdk_test.models import components
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DtoCreateAPIKeyRequestTypedDict(TypedDict):
    name: str
    type: TypesSecretType
    expires_at: NotRequired[str]
    service_account_id: NotRequired[str]


class DtoCreateAPIKeyRequest(BaseModel):
    name: str

    type: TypesSecretType

    expires_at: Optional[str] = None

    service_account_id: Optional[str] = None

    @field_serializer("type")
    def serialize_type(self, value):
        if isinstance(value, str):
            try:
                return components.TypesSecretType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["expires_at", "service_account_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
