"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_costsheetresponse import DtoCostsheetResponse, DtoCostsheetResponseTypedDict
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DtoCreateCostsheetResponseTypedDict(TypedDict):
    costsheet: NotRequired[DtoCostsheetResponseTypedDict]


class DtoCreateCostsheetResponse(BaseModel):
    costsheet: Optional[DtoCostsheetResponse] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["costsheet"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
