"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .types_connectionmetadata import (
    TypesConnectionMetadata,
    TypesConnectionMetadataTypedDict,
)
from .types_syncconfig import TypesSyncConfig, TypesSyncConfigTypedDict
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class DtoUpdateConnectionRequestTypedDict(TypedDict):
    encrypted_secret_data: NotRequired[TypesConnectionMetadataTypedDict]
    metadata: NotRequired[Dict[str, Any]]
    name: NotRequired[str]
    sync_config: NotRequired[TypesSyncConfigTypedDict]


class DtoUpdateConnectionRequest(BaseModel):
    encrypted_secret_data: Optional[TypesConnectionMetadata] = None

    metadata: Optional[Dict[str, Any]] = None

    name: Optional[str] = None

    sync_config: Optional[TypesSyncConfig] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["encrypted_secret_data", "metadata", "name", "sync_config"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
