"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_debugtracker import DtoDebugTracker, DtoDebugTrackerTypedDict
from .dto_event import DtoEvent, DtoEventTypedDict
from .dto_featureusageinfo import DtoFeatureUsageInfo, DtoFeatureUsageInfoTypedDict
from .types_eventprocessingstatustype import TypesEventProcessingStatusType
from flexprice_sdk_test.models import components
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class DtoGetEventByIDResponseTypedDict(TypedDict):
    debug_tracker: NotRequired[DtoDebugTrackerTypedDict]
    event: NotRequired[DtoEventTypedDict]
    processed_events: NotRequired[List[DtoFeatureUsageInfoTypedDict]]
    status: NotRequired[TypesEventProcessingStatusType]


class DtoGetEventByIDResponse(BaseModel):
    debug_tracker: Optional[DtoDebugTracker] = None

    event: Optional[DtoEvent] = None

    processed_events: Optional[List[DtoFeatureUsageInfo]] = None

    status: Optional[TypesEventProcessingStatusType] = None

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return components.TypesEventProcessingStatusType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["debug_tracker", "event", "processed_events", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
