"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_createpricetier import DtoCreatePriceTier, DtoCreatePriceTierTypedDict
from .price_transformquantity import (
    PriceTransformQuantity,
    PriceTransformQuantityTypedDict,
)
from .types_billingmodel import TypesBillingModel
from .types_billingtier import TypesBillingTier
from .types_commitmenttype import TypesCommitmentType
from flexprice_sdk_test.models import components
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class DtoUpdateSubscriptionLineItemRequestTypedDict(TypedDict):
    amount: NotRequired[str]
    r"""Amount is the new price amount that overrides the original price"""
    billing_model: NotRequired[TypesBillingModel]
    commitment_amount: NotRequired[float]
    r"""Commitment fields"""
    commitment_overage_factor: NotRequired[float]
    commitment_quantity: NotRequired[float]
    commitment_true_up_enabled: NotRequired[bool]
    commitment_type: NotRequired[TypesCommitmentType]
    commitment_windowed: NotRequired[bool]
    effective_from: NotRequired[str]
    r"""EffectiveFrom for the existing line item (if not provided, defaults to now)"""
    metadata: NotRequired[Dict[str, str]]
    r"""Metadata for the new line item"""
    tier_mode: NotRequired[TypesBillingTier]
    tiers: NotRequired[List[DtoCreatePriceTierTypedDict]]
    r"""Tiers determines the pricing tiers for this line item"""
    transform_quantity: NotRequired[PriceTransformQuantityTypedDict]


class DtoUpdateSubscriptionLineItemRequest(BaseModel):
    amount: Optional[str] = None
    r"""Amount is the new price amount that overrides the original price"""

    billing_model: Optional[TypesBillingModel] = None

    commitment_amount: Optional[float] = None
    r"""Commitment fields"""

    commitment_overage_factor: Optional[float] = None

    commitment_quantity: Optional[float] = None

    commitment_true_up_enabled: Optional[bool] = None

    commitment_type: Optional[TypesCommitmentType] = None

    commitment_windowed: Optional[bool] = None

    effective_from: Optional[str] = None
    r"""EffectiveFrom for the existing line item (if not provided, defaults to now)"""

    metadata: Optional[Dict[str, str]] = None
    r"""Metadata for the new line item"""

    tier_mode: Optional[TypesBillingTier] = None

    tiers: Optional[List[DtoCreatePriceTier]] = None
    r"""Tiers determines the pricing tiers for this line item"""

    transform_quantity: Optional[PriceTransformQuantity] = None

    @field_serializer("billing_model")
    def serialize_billing_model(self, value):
        if isinstance(value, str):
            try:
                return components.TypesBillingModel(value)
            except ValueError:
                return value
        return value

    @field_serializer("commitment_type")
    def serialize_commitment_type(self, value):
        if isinstance(value, str):
            try:
                return components.TypesCommitmentType(value)
            except ValueError:
                return value
        return value

    @field_serializer("tier_mode")
    def serialize_tier_mode(self, value):
        if isinstance(value, str):
            try:
                return components.TypesBillingTier(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "amount",
                "billing_model",
                "commitment_amount",
                "commitment_overage_factor",
                "commitment_quantity",
                "commitment_true_up_enabled",
                "commitment_type",
                "commitment_windowed",
                "effective_from",
                "metadata",
                "tier_mode",
                "tiers",
                "transform_quantity",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
