"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_matchedprice import DtoMatchedPrice, DtoMatchedPriceTypedDict
from .errors_errorresponse import ErrorsErrorResponse, ErrorsErrorResponseTypedDict
from .types_debugtrackerstatus import TypesDebugTrackerStatus
from flexprice_sdk_test.models import components
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class DtoPriceLookupResultTypedDict(TypedDict):
    error: NotRequired[ErrorsErrorResponseTypedDict]
    matched_prices: NotRequired[List[DtoMatchedPriceTypedDict]]
    status: NotRequired[TypesDebugTrackerStatus]


class DtoPriceLookupResult(BaseModel):
    error: Optional[ErrorsErrorResponse] = None

    matched_prices: Optional[List[DtoMatchedPrice]] = None

    status: Optional[TypesDebugTrackerStatus] = None

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return components.TypesDebugTrackerStatus(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["error", "matched_prices", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
