"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .types_s3jobconfig import TypesS3JobConfig, TypesS3JobConfigTypedDict
from .types_scheduledtaskentitytype import TypesScheduledTaskEntityType
from .types_scheduledtaskinterval import TypesScheduledTaskInterval
from flexprice_sdk_test.models import components
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DtoCreateScheduledTaskRequestTypedDict(TypedDict):
    connection_id: str
    entity_type: TypesScheduledTaskEntityType
    interval: TypesScheduledTaskInterval
    job_config: TypesS3JobConfigTypedDict
    enabled: NotRequired[bool]


class DtoCreateScheduledTaskRequest(BaseModel):
    connection_id: str

    entity_type: TypesScheduledTaskEntityType

    interval: TypesScheduledTaskInterval

    job_config: TypesS3JobConfig

    enabled: Optional[bool] = None

    @field_serializer("entity_type")
    def serialize_entity_type(self, value):
        if isinstance(value, str):
            try:
                return components.TypesScheduledTaskEntityType(value)
            except ValueError:
                return value
        return value

    @field_serializer("interval")
    def serialize_interval(self, value):
        if isinstance(value, str):
            try:
                return components.TypesScheduledTaskInterval(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["enabled"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
