"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .types_coupontype import TypesCouponType
from .types_status import TypesStatus
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class DtoCouponApplicationResponseTypedDict(TypedDict):
    applied_at: NotRequired[str]
    coupon_association_id: NotRequired[str]
    coupon_id: NotRequired[str]
    coupon_snapshot: NotRequired[Dict[str, Any]]
    created_at: NotRequired[str]
    created_by: NotRequired[str]
    currency: NotRequired[str]
    discount_percentage: NotRequired[str]
    discount_type: NotRequired[TypesCouponType]
    discounted_amount: NotRequired[str]
    environment_id: NotRequired[str]
    final_price: NotRequired[str]
    id: NotRequired[str]
    invoice_id: NotRequired[str]
    invoice_line_item_id: NotRequired[str]
    metadata: NotRequired[Dict[str, str]]
    original_price: NotRequired[str]
    status: NotRequired[TypesStatus]
    subscription_id: NotRequired[str]
    tenant_id: NotRequired[str]
    updated_at: NotRequired[str]
    updated_by: NotRequired[str]


class DtoCouponApplicationResponse(BaseModel):
    applied_at: Optional[str] = None

    coupon_association_id: Optional[str] = None

    coupon_id: Optional[str] = None

    coupon_snapshot: Optional[Dict[str, Any]] = None

    created_at: Optional[str] = None

    created_by: Optional[str] = None

    currency: Optional[str] = None

    discount_percentage: Optional[str] = None

    discount_type: Optional[TypesCouponType] = None

    discounted_amount: Optional[str] = None

    environment_id: Optional[str] = None

    final_price: Optional[str] = None

    id: Optional[str] = None

    invoice_id: Optional[str] = None

    invoice_line_item_id: Optional[str] = None

    metadata: Optional[Dict[str, str]] = None

    original_price: Optional[str] = None

    status: Optional[TypesStatus] = None

    subscription_id: Optional[str] = None

    tenant_id: Optional[str] = None

    updated_at: Optional[str] = None

    updated_by: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "applied_at",
                "coupon_association_id",
                "coupon_id",
                "coupon_snapshot",
                "created_at",
                "created_by",
                "currency",
                "discount_percentage",
                "discount_type",
                "discounted_amount",
                "environment_id",
                "final_price",
                "id",
                "invoice_id",
                "invoice_line_item_id",
                "metadata",
                "original_price",
                "status",
                "subscription_id",
                "tenant_id",
                "updated_at",
                "updated_by",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
