"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .types_subscriptionschedulechangetype import TypesSubscriptionScheduleChangeType
from flexprice_sdk_test.models import components
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DtoCancelScheduleRequestTypedDict(TypedDict):
    r"""Request to cancel a subscription schedule (supports two modes)"""

    schedule_id: NotRequired[str]
    r"""schedule_id is the ID of the schedule to cancel (optional if subscription_id and schedule_type are provided)"""
    schedule_type: NotRequired[TypesSubscriptionScheduleChangeType]
    subscription_id: NotRequired[str]
    r"""subscription_id is the ID of the subscription (required if schedule_id is not provided)"""


class DtoCancelScheduleRequest(BaseModel):
    r"""Request to cancel a subscription schedule (supports two modes)"""

    schedule_id: Optional[str] = None
    r"""schedule_id is the ID of the schedule to cancel (optional if subscription_id and schedule_type are provided)"""

    schedule_type: Optional[TypesSubscriptionScheduleChangeType] = None

    subscription_id: Optional[str] = None
    r"""subscription_id is the ID of the subscription (required if schedule_id is not provided)"""

    @field_serializer("schedule_type")
    def serialize_schedule_type(self, value):
        if isinstance(value, str):
            try:
                return components.TypesSubscriptionScheduleChangeType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["schedule_id", "schedule_type", "subscription_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
