"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_entitlementsourceentitytype import DtoEntitlementSourceEntityType
from .types_billingperiod import TypesBillingPeriod
from flexprice_sdk_test.models import components
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DtoEntitlementSourceTypedDict(TypedDict):
    entitlement_id: NotRequired[str]
    entity_id: NotRequired[str]
    entity_name: NotRequired[str]
    entity_type: NotRequired[DtoEntitlementSourceEntityType]
    is_enabled: NotRequired[bool]
    quantity: NotRequired[int]
    static_value: NotRequired[str]
    subscription_id: NotRequired[str]
    usage_limit: NotRequired[int]
    usage_reset_period: NotRequired[TypesBillingPeriod]


class DtoEntitlementSource(BaseModel):
    entitlement_id: Optional[str] = None

    entity_id: Optional[str] = None

    entity_name: Optional[str] = None

    entity_type: Optional[DtoEntitlementSourceEntityType] = None

    is_enabled: Optional[bool] = None

    quantity: Optional[int] = None

    static_value: Optional[str] = None

    subscription_id: Optional[str] = None

    usage_limit: Optional[int] = None

    usage_reset_period: Optional[TypesBillingPeriod] = None

    @field_serializer("entity_type")
    def serialize_entity_type(self, value):
        if isinstance(value, str):
            try:
                return components.DtoEntitlementSourceEntityType(value)
            except ValueError:
                return value
        return value

    @field_serializer("usage_reset_period")
    def serialize_usage_reset_period(self, value):
        if isinstance(value, str):
            try:
                return components.TypesBillingPeriod(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "entitlement_id",
                "entity_id",
                "entity_name",
                "entity_type",
                "is_enabled",
                "quantity",
                "static_value",
                "subscription_id",
                "usage_limit",
                "usage_reset_period",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
