"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .types_billingcadence import TypesBillingCadence
from .types_billingcycle import TypesBillingCycle
from .types_billingperiod import TypesBillingPeriod
from .types_prorationbehavior import TypesProrationBehavior
from .types_scheduletype import TypesScheduleType
from flexprice_sdk_test.models import components
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class DtoSubscriptionChangeRequestTypedDict(TypedDict):
    r"""Request object for changing a subscription plan (upgrade/downgrade)"""

    billing_cadence: TypesBillingCadence
    billing_cycle: TypesBillingCycle
    billing_period: TypesBillingPeriod
    proration_behavior: TypesProrationBehavior
    target_plan_id: str
    r"""target_plan_id is the ID of the new plan to change to (required)"""
    billing_period_count: NotRequired[int]
    r"""billing_period_count is the billing period count for the new subscription"""
    change_at: NotRequired[TypesScheduleType]
    metadata: NotRequired[Dict[str, str]]
    r"""metadata contains additional key-value pairs for storing extra information"""


class DtoSubscriptionChangeRequest(BaseModel):
    r"""Request object for changing a subscription plan (upgrade/downgrade)"""

    billing_cadence: TypesBillingCadence

    billing_cycle: TypesBillingCycle

    billing_period: TypesBillingPeriod

    proration_behavior: TypesProrationBehavior

    target_plan_id: str
    r"""target_plan_id is the ID of the new plan to change to (required)"""

    billing_period_count: Optional[int] = None
    r"""billing_period_count is the billing period count for the new subscription"""

    change_at: Optional[TypesScheduleType] = None

    metadata: Optional[Dict[str, str]] = None
    r"""metadata contains additional key-value pairs for storing extra information"""

    @field_serializer("billing_cadence")
    def serialize_billing_cadence(self, value):
        if isinstance(value, str):
            try:
                return components.TypesBillingCadence(value)
            except ValueError:
                return value
        return value

    @field_serializer("billing_cycle")
    def serialize_billing_cycle(self, value):
        if isinstance(value, str):
            try:
                return components.TypesBillingCycle(value)
            except ValueError:
                return value
        return value

    @field_serializer("billing_period")
    def serialize_billing_period(self, value):
        if isinstance(value, str):
            try:
                return components.TypesBillingPeriod(value)
            except ValueError:
                return value
        return value

    @field_serializer("proration_behavior")
    def serialize_proration_behavior(self, value):
        if isinstance(value, str):
            try:
                return components.TypesProrationBehavior(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["billing_period_count", "change_at", "metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
