"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_createpricetier import DtoCreatePriceTier, DtoCreatePriceTierTypedDict
from .dto_priceunitconfig import DtoPriceUnitConfig, DtoPriceUnitConfigTypedDict
from .price_transformquantity import (
    PriceTransformQuantity,
    PriceTransformQuantityTypedDict,
)
from .types_billingcadence import TypesBillingCadence
from .types_billingmodel import TypesBillingModel
from .types_billingperiod import TypesBillingPeriod
from .types_billingtier import TypesBillingTier
from .types_invoicecadence import TypesInvoiceCadence
from .types_priceentitytype import TypesPriceEntityType
from .types_pricetype import TypesPriceType
from .types_priceunittype import TypesPriceUnitType
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class DtoCreatePriceRequestTypedDict(TypedDict):
    billing_cadence: TypesBillingCadence
    billing_model: TypesBillingModel
    billing_period: TypesBillingPeriod
    currency: str
    entity_id: str
    entity_type: TypesPriceEntityType
    invoice_cadence: TypesInvoiceCadence
    price_unit_type: TypesPriceUnitType
    type: TypesPriceType
    amount: NotRequired[str]
    billing_period_count: NotRequired[int]
    description: NotRequired[str]
    display_name: NotRequired[str]
    end_date: NotRequired[str]
    filter_values: NotRequired[Dict[str, List[str]]]
    group_id: NotRequired[str]
    r"""GroupID is the id of the group to add the price to"""
    lookup_key: NotRequired[str]
    metadata: NotRequired[Dict[str, str]]
    meter_id: NotRequired[str]
    min_quantity: NotRequired[int]
    r"""MinQuantity is the minimum quantity of the price"""
    price_unit_config: NotRequired[DtoPriceUnitConfigTypedDict]
    start_date: NotRequired[str]
    tier_mode: NotRequired[TypesBillingTier]
    tiers: NotRequired[List[DtoCreatePriceTierTypedDict]]
    transform_quantity: NotRequired[PriceTransformQuantityTypedDict]
    trial_period: NotRequired[int]


class DtoCreatePriceRequest(BaseModel):
    billing_cadence: TypesBillingCadence

    billing_model: TypesBillingModel

    billing_period: TypesBillingPeriod

    currency: str

    entity_id: str

    entity_type: TypesPriceEntityType

    invoice_cadence: TypesInvoiceCadence

    price_unit_type: TypesPriceUnitType

    type: TypesPriceType

    amount: Optional[str] = None

    billing_period_count: Optional[int] = None

    description: Optional[str] = None

    display_name: Optional[str] = None

    end_date: Optional[str] = None

    filter_values: Optional[Dict[str, List[str]]] = None

    group_id: Optional[str] = None
    r"""GroupID is the id of the group to add the price to"""

    lookup_key: Optional[str] = None

    metadata: Optional[Dict[str, str]] = None

    meter_id: Optional[str] = None

    min_quantity: Optional[int] = None
    r"""MinQuantity is the minimum quantity of the price"""

    price_unit_config: Optional[DtoPriceUnitConfig] = None

    start_date: Optional[str] = None

    tier_mode: Optional[TypesBillingTier] = None

    tiers: Optional[List[DtoCreatePriceTier]] = None

    transform_quantity: Optional[PriceTransformQuantity] = None

    trial_period: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "amount",
                "billing_period_count",
                "description",
                "display_name",
                "end_date",
                "filter_values",
                "group_id",
                "lookup_key",
                "metadata",
                "meter_id",
                "min_quantity",
                "price_unit_config",
                "start_date",
                "tier_mode",
                "tiers",
                "transform_quantity",
                "trial_period",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
