"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_aggregatedfeature import DtoAggregatedFeature, DtoAggregatedFeatureTypedDict
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class DtoCustomerEntitlementsResponseTypedDict(TypedDict):
    customer_id: NotRequired[str]
    features: NotRequired[List[DtoAggregatedFeatureTypedDict]]


class DtoCustomerEntitlementsResponse(BaseModel):
    customer_id: Optional[str] = None

    features: Optional[List[DtoAggregatedFeature]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["customer_id", "features"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
