"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from flexprice_sdk_test import utils


class TypesEntitlementEntityType(str, Enum, metaclass=utils.OpenEnumMeta):
    PLAN = "PLAN"
    SUBSCRIPTION = "SUBSCRIPTION"
    ADDON = "ADDON"
