"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .types_filtercondition import TypesFilterCondition, TypesFilterConditionTypedDict
from .types_sortcondition import TypesSortCondition, TypesSortConditionTypedDict
from .types_status import TypesStatus
from enum import Enum
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TypesFeatureFilterOrder(str, Enum):
    ASC = "asc"
    DESC = "desc"


class TypesFeatureFilterTypedDict(TypedDict):
    end_time: NotRequired[str]
    expand: NotRequired[str]
    feature_ids: NotRequired[List[str]]
    r"""Feature specific filters"""
    filters: NotRequired[List[TypesFilterConditionTypedDict]]
    r"""filters allows complex filtering based on multiple fields"""
    limit: NotRequired[int]
    lookup_key: NotRequired[str]
    lookup_keys: NotRequired[List[str]]
    meter_ids: NotRequired[List[str]]
    name_contains: NotRequired[str]
    offset: NotRequired[int]
    order: NotRequired[TypesFeatureFilterOrder]
    sort: NotRequired[List[TypesSortConditionTypedDict]]
    start_time: NotRequired[str]
    status: NotRequired[TypesStatus]


class TypesFeatureFilter(BaseModel):
    end_time: Optional[str] = None

    expand: Optional[str] = None

    feature_ids: Optional[List[str]] = None
    r"""Feature specific filters"""

    filters: Optional[List[TypesFilterCondition]] = None
    r"""filters allows complex filtering based on multiple fields"""

    limit: Optional[int] = None

    lookup_key: Optional[str] = None

    lookup_keys: Optional[List[str]] = None

    meter_ids: Optional[List[str]] = None

    name_contains: Optional[str] = None

    offset: Optional[int] = None

    order: Optional[TypesFeatureFilterOrder] = None

    sort: Optional[List[TypesSortCondition]] = None

    start_time: Optional[str] = None

    status: Optional[TypesStatus] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "end_time",
                "expand",
                "feature_ids",
                "filters",
                "limit",
                "lookup_key",
                "lookup_keys",
                "meter_ids",
                "name_contains",
                "offset",
                "order",
                "sort",
                "start_time",
                "status",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
