"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class TypesCancelImmediatelyInvoicePolicy(str, Enum):
    GENERATE_INVOICE = "generate_invoice"
    SKIP = "skip"
