"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TypesQuickBooksConnectionMetadataTypedDict(TypedDict):
    access_token: NotRequired[str]
    r"""Managed internally - set after auth code exchange or token refresh"""
    auth_code: NotRequired[str]
    r"""Optional - for initial setup via auth code (will be cleared after token exchange)"""
    client_id: NotRequired[str]
    r"""Required for initial connection setup"""
    client_secret: NotRequired[str]
    r"""OAuth Client Secret (encrypted)"""
    environment: NotRequired[str]
    r"""\"sandbox\" or \"production\" """
    income_account_id: NotRequired[str]
    r"""Optional configuration"""
    oauth_session_data: NotRequired[str]
    r"""Temporary OAuth session data (only used during OAuth flow, cleared after completion)"""
    realm_id: NotRequired[str]
    r"""QuickBooks Company ID (not encrypted)"""
    redirect_uri: NotRequired[str]
    r"""OAuth Redirect URI (temporary)"""
    refresh_token: NotRequired[str]
    r"""OAuth Refresh Token (encrypted)"""
    webhook_verifier_token: NotRequired[str]
    r"""Webhook security"""


class TypesQuickBooksConnectionMetadata(BaseModel):
    access_token: Optional[str] = None
    r"""Managed internally - set after auth code exchange or token refresh"""

    auth_code: Optional[str] = None
    r"""Optional - for initial setup via auth code (will be cleared after token exchange)"""

    client_id: Optional[str] = None
    r"""Required for initial connection setup"""

    client_secret: Optional[str] = None
    r"""OAuth Client Secret (encrypted)"""

    environment: Optional[str] = None
    r"""\"sandbox\" or \"production\" """

    income_account_id: Optional[str] = None
    r"""Optional configuration"""

    oauth_session_data: Optional[str] = None
    r"""Temporary OAuth session data (only used during OAuth flow, cleared after completion)"""

    realm_id: Optional[str] = None
    r"""QuickBooks Company ID (not encrypted)"""

    redirect_uri: Optional[str] = None
    r"""OAuth Redirect URI (temporary)"""

    refresh_token: Optional[str] = None
    r"""OAuth Refresh Token (encrypted)"""

    webhook_verifier_token: Optional[str] = None
    r"""Webhook security"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "access_token",
                "auth_code",
                "client_id",
                "client_secret",
                "environment",
                "income_account_id",
                "oauth_session_data",
                "realm_id",
                "redirect_uri",
                "refresh_token",
                "webhook_verifier_token",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
