"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from flexprice_sdk_test import utils


class TypesIntegrationEntityType(str, Enum, metaclass=utils.OpenEnumMeta):
    CUSTOMER = "customer"
    PLAN = "plan"
    INVOICE = "invoice"
    SUBSCRIPTION = "subscription"
    PAYMENT = "payment"
    CREDIT_NOTE = "credit_note"
    ADDON = "addon"
    ITEM = "item"
    ITEM_PRICE = "item_price"
    PRICE = "price"
