"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .types_chargebeeconnectionmetadata import (
    TypesChargebeeConnectionMetadata,
    TypesChargebeeConnectionMetadataTypedDict,
)
from .types_connectionsettings import (
    TypesConnectionSettings,
    TypesConnectionSettingsTypedDict,
)
from .types_genericconnectionmetadata import (
    TypesGenericConnectionMetadata,
    TypesGenericConnectionMetadataTypedDict,
)
from .types_hubspotconnectionmetadata import (
    TypesHubSpotConnectionMetadata,
    TypesHubSpotConnectionMetadataTypedDict,
)
from .types_moyasarconnectionmetadata import (
    TypesMoyasarConnectionMetadata,
    TypesMoyasarConnectionMetadataTypedDict,
)
from .types_nomodconnectionmetadata import (
    TypesNomodConnectionMetadata,
    TypesNomodConnectionMetadataTypedDict,
)
from .types_quickbooksconnectionmetadata import (
    TypesQuickBooksConnectionMetadata,
    TypesQuickBooksConnectionMetadataTypedDict,
)
from .types_razorpayconnectionmetadata import (
    TypesRazorpayConnectionMetadata,
    TypesRazorpayConnectionMetadataTypedDict,
)
from .types_s3connectionmetadata import (
    TypesS3ConnectionMetadata,
    TypesS3ConnectionMetadataTypedDict,
)
from .types_stripeconnectionmetadata import (
    TypesStripeConnectionMetadata,
    TypesStripeConnectionMetadataTypedDict,
)
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TypesConnectionMetadataTypedDict(TypedDict):
    chargebee: NotRequired[TypesChargebeeConnectionMetadataTypedDict]
    generic: NotRequired[TypesGenericConnectionMetadataTypedDict]
    hubspot: NotRequired[TypesHubSpotConnectionMetadataTypedDict]
    moyasar: NotRequired[TypesMoyasarConnectionMetadataTypedDict]
    nomod: NotRequired[TypesNomodConnectionMetadataTypedDict]
    quickbooks: NotRequired[TypesQuickBooksConnectionMetadataTypedDict]
    razorpay: NotRequired[TypesRazorpayConnectionMetadataTypedDict]
    s3: NotRequired[TypesS3ConnectionMetadataTypedDict]
    settings: NotRequired[TypesConnectionSettingsTypedDict]
    stripe: NotRequired[TypesStripeConnectionMetadataTypedDict]


class TypesConnectionMetadata(BaseModel):
    chargebee: Optional[TypesChargebeeConnectionMetadata] = None

    generic: Optional[TypesGenericConnectionMetadata] = None

    hubspot: Optional[TypesHubSpotConnectionMetadata] = None

    moyasar: Optional[TypesMoyasarConnectionMetadata] = None

    nomod: Optional[TypesNomodConnectionMetadata] = None

    quickbooks: Optional[TypesQuickBooksConnectionMetadata] = None

    razorpay: Optional[TypesRazorpayConnectionMetadata] = None

    s3: Optional[TypesS3ConnectionMetadata] = None

    settings: Optional[TypesConnectionSettings] = None

    stripe: Optional[TypesStripeConnectionMetadata] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "chargebee",
                "generic",
                "hubspot",
                "moyasar",
                "nomod",
                "quickbooks",
                "razorpay",
                "s3",
                "settings",
                "stripe",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
