"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from flexprice_sdk_test import utils


class TypesAggregationType(str, Enum, metaclass=utils.OpenEnumMeta):
    COUNT = "COUNT"
    SUM = "SUM"
    AVG = "AVG"
    COUNT_UNIQUE = "COUNT_UNIQUE"
    LATEST = "LATEST"
    SUM_WITH_MULTIPLIER = "SUM_WITH_MULTIPLIER"
    MAX = "MAX"
    WEIGHTED_SUM = "WEIGHTED_SUM"
