"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from flexprice_sdk_test import utils


class TypesWalletTxReferenceType(str, Enum, metaclass=utils.OpenEnumMeta):
    PAYMENT = "PAYMENT"
    EXTERNAL = "EXTERNAL"
    REQUEST = "REQUEST"
    INVOICE = "INVOICE"
