"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from flexprice_sdk_test import utils


class TypesDebugTrackerStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    UNPROCESSED = "unprocessed"
    NOT_FOUND = "not_found"
    FOUND = "found"
    ERROR = "error"
