"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from flexprice_sdk_test import utils


class TypesAlertState(str, Enum, metaclass=utils.OpenEnumMeta):
    OK = "ok"
    INFO = "info"
    WARNING = "warning"
    IN_ALARM = "in_alarm"
