"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class TypesScheduleType(str, Enum):
    IMMEDIATE = "immediate"
    END_OF_PERIOD = "end_of_period"
