"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class TypesSubscriptionScheduleChangeType(str, Enum):
    PLAN_CHANGE = "plan_change"
    CANCELLATION = "cancellation"
