"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TypesRazorpayConnectionMetadataTypedDict(TypedDict):
    key_id: NotRequired[str]
    r"""Razorpay Key ID (encrypted)"""
    secret_key: NotRequired[str]
    r"""Razorpay Secret Key (encrypted)"""
    webhook_secret: NotRequired[str]
    r"""Razorpay Webhook Secret (encrypted, optional)"""


class TypesRazorpayConnectionMetadata(BaseModel):
    key_id: Optional[str] = None
    r"""Razorpay Key ID (encrypted)"""

    secret_key: Optional[str] = None
    r"""Razorpay Secret Key (encrypted)"""

    webhook_secret: Optional[str] = None
    r"""Razorpay Webhook Secret (encrypted, optional)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["key_id", "secret_key", "webhook_secret"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
