"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from flexprice_sdk_test import utils


class TypesTaxRateType(str, Enum, metaclass=utils.OpenEnumMeta):
    PERCENTAGE = "percentage"
    FIXED = "fixed"
