"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from flexprice_sdk_test import utils


class TypesEntitlementUsageResetPeriod(str, Enum, metaclass=utils.OpenEnumMeta):
    MONTHLY = "MONTHLY"
    ANNUAL = "ANNUAL"
    WEEKLY = "WEEKLY"
    DAILY = "DAILY"
    QUARTERLY = "QUARTERLY"
    HALF_YEARLY = "HALF_YEARLY"
    NEVER = "NEVER"
