"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .types_filtercondition import TypesFilterCondition, TypesFilterConditionTypedDict
from .types_secretprovider import TypesSecretProvider
from .types_sortcondition import TypesSortCondition, TypesSortConditionTypedDict
from .types_status import TypesStatus
from enum import Enum
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TypesConnectionFilterOrder(str, Enum):
    ASC = "asc"
    DESC = "desc"


class TypesConnectionFilterTypedDict(TypedDict):
    connection_ids: NotRequired[List[str]]
    end_time: NotRequired[str]
    expand: NotRequired[str]
    filters: NotRequired[List[TypesFilterConditionTypedDict]]
    limit: NotRequired[int]
    offset: NotRequired[int]
    order: NotRequired[TypesConnectionFilterOrder]
    provider_type: NotRequired[TypesSecretProvider]
    sort: NotRequired[List[TypesSortConditionTypedDict]]
    start_time: NotRequired[str]
    status: NotRequired[TypesStatus]


class TypesConnectionFilter(BaseModel):
    connection_ids: Optional[List[str]] = None

    end_time: Optional[str] = None

    expand: Optional[str] = None

    filters: Optional[List[TypesFilterCondition]] = None

    limit: Optional[int] = None

    offset: Optional[int] = None

    order: Optional[TypesConnectionFilterOrder] = None

    provider_type: Optional[TypesSecretProvider] = None

    sort: Optional[List[TypesSortCondition]] = None

    start_time: Optional[str] = None

    status: Optional[TypesStatus] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "connection_ids",
                "end_time",
                "expand",
                "filters",
                "limit",
                "offset",
                "order",
                "provider_type",
                "sort",
                "start_time",
                "status",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
