"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .types_s3compressiontype import TypesS3CompressionType
from .types_s3encryptiontype import TypesS3EncryptionType
from flexprice_sdk_test.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TypesS3ExportConfigTypedDict(TypedDict):
    bucket: NotRequired[str]
    r"""S3 bucket name"""
    compression: NotRequired[TypesS3CompressionType]
    encryption: NotRequired[TypesS3EncryptionType]
    is_flexprice_managed: NotRequired[bool]
    r"""If true, use Flexprice-managed S3 credentials instead of user-provided"""
    key_prefix: NotRequired[str]
    r"""Optional prefix for S3 keys (e.g., \"flexprice-exports/\")"""
    region: NotRequired[str]
    r"""AWS region (e.g., \"us-west-2\")"""


class TypesS3ExportConfig(BaseModel):
    bucket: Optional[str] = None
    r"""S3 bucket name"""

    compression: Optional[TypesS3CompressionType] = None

    encryption: Optional[TypesS3EncryptionType] = None

    is_flexprice_managed: Optional[bool] = None
    r"""If true, use Flexprice-managed S3 credentials instead of user-provided"""

    key_prefix: Optional[str] = None
    r"""Optional prefix for S3 keys (e.g., \"flexprice-exports/\")"""

    region: Optional[str] = None
    r"""AWS region (e.g., \"us-west-2\")"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "bucket",
                "compression",
                "encryption",
                "is_flexprice_managed",
                "key_prefix",
                "region",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
