"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class TypesEventProcessingStatusType(str, Enum):
    PROCESSED = "processed"
    PROCESSING = "processing"
    FAILED = "failed"
