"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_activatedraftsubscriptionrequest import (
    DtoActivateDraftSubscriptionRequest,
    DtoActivateDraftSubscriptionRequestTypedDict,
)
from flexprice_temp.types import BaseModel
from flexprice_temp.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ActivateSubscriptionRequestTypedDict(TypedDict):
    id: str
    r"""Subscription ID"""
    body: DtoActivateDraftSubscriptionRequestTypedDict
    r"""Activate Draft Subscription Request"""


class ActivateSubscriptionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Subscription ID"""

    body: Annotated[
        DtoActivateDraftSubscriptionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Activate Draft Subscription Request"""
