"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_cancelsubscriptionrequest import (
    DtoCancelSubscriptionRequest,
    DtoCancelSubscriptionRequestTypedDict,
)
from flexprice_temp.types import BaseModel
from flexprice_temp.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class CancelSubscriptionRequestTypedDict(TypedDict):
    id: str
    r"""Subscription ID"""
    body: DtoCancelSubscriptionRequestTypedDict
    r"""Cancel Subscription Request"""


class CancelSubscriptionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Subscription ID"""

    body: Annotated[
        DtoCancelSubscriptionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Cancel Subscription Request"""
