"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_deletecreditgrantrequest import (
    DtoDeleteCreditGrantRequest,
    DtoDeleteCreditGrantRequestTypedDict,
)
from flexprice_temp.types import BaseModel, UNSET_SENTINEL
from flexprice_temp.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeleteCreditGrantRequestTypedDict(TypedDict):
    id: str
    r"""Credit Grant ID"""
    body: NotRequired[DtoDeleteCreditGrantRequestTypedDict]
    r"""Optional: effective_date for subscription-scoped grants"""


class DeleteCreditGrantRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Credit Grant ID"""

    body: Annotated[
        Optional[DtoDeleteCreditGrantRequest],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
    r"""Optional: effective_date for subscription-scoped grants"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["body"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
