"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_temp.types import BaseModel
from flexprice_temp.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetPriceUnitRequestTypedDict(TypedDict):
    id: str
    r"""Price unit ID"""


class GetPriceUnitRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Price unit ID"""
