"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_resumesubscriptionrequest import (
    DtoResumeSubscriptionRequest,
    DtoResumeSubscriptionRequestTypedDict,
)
from flexprice_temp.types import BaseModel
from flexprice_temp.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ResumeSubscriptionRequestTypedDict(TypedDict):
    id: str
    r"""Subscription ID"""
    body: DtoResumeSubscriptionRequestTypedDict
    r"""Resume subscription request"""


class ResumeSubscriptionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Subscription ID"""

    body: Annotated[
        DtoResumeSubscriptionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Resume subscription request"""
