"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_temp.types import UnrecognizedStr
from typing import Literal, Union


TypesTaxRateEntityType = Union[
    Literal[
        "customer",
        "subscription",
        "invoice",
        "tenant",
    ],
    UnrecognizedStr,
]
