"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_temp.types import UnrecognizedStr
from typing import Literal, Union


TypesScheduledTaskEntityType = Union[
    Literal[
        "events",
        "invoice",
        "credit_topups",
        "credit_usage",
    ],
    UnrecognizedStr,
]
