"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_temp.types import UnrecognizedStr
from typing import Literal, Union


TypesS3EncryptionType = Union[
    Literal[
        "AES256",
        "aws:kms",
        "aws:kms:dsse",
    ],
    UnrecognizedStr,
]
