"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_updatesubscriptionlineitemrequest import (
    DtoUpdateSubscriptionLineItemRequest,
    DtoUpdateSubscriptionLineItemRequestTypedDict,
)
from flexprice_temp.types import BaseModel
from flexprice_temp.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateSubscriptionLineItemRequestTypedDict(TypedDict):
    id: str
    r"""Line Item ID"""
    body: DtoUpdateSubscriptionLineItemRequestTypedDict
    r"""Update Line Item Request"""


class UpdateSubscriptionLineItemRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Line Item ID"""

    body: Annotated[
        DtoUpdateSubscriptionLineItemRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Update Line Item Request"""
