"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_updatesubscriptionrequest import (
    DtoUpdateSubscriptionRequest,
    DtoUpdateSubscriptionRequestTypedDict,
)
from flexprice_temp.types import BaseModel
from flexprice_temp.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateSubscriptionRequestTypedDict(TypedDict):
    id: str
    r"""Subscription ID"""
    body: DtoUpdateSubscriptionRequestTypedDict
    r"""Update Subscription Request"""


class UpdateSubscriptionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Subscription ID"""

    body: Annotated[
        DtoUpdateSubscriptionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Update Subscription Request"""
