"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_updatecouponrequest import (
    DtoUpdateCouponRequest,
    DtoUpdateCouponRequestTypedDict,
)
from flexprice_temp.types import BaseModel
from flexprice_temp.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateCouponRequestTypedDict(TypedDict):
    id: str
    r"""Coupon ID"""
    body: DtoUpdateCouponRequestTypedDict
    r"""Coupon update request"""


class UpdateCouponRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Coupon ID"""

    body: Annotated[
        DtoUpdateCouponRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Coupon update request"""
