"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_taxassociationupdaterequest import (
    DtoTaxAssociationUpdateRequest,
    DtoTaxAssociationUpdateRequestTypedDict,
)
from flexprice_temp.types import BaseModel
from flexprice_temp.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateTaxAssociationRequestTypedDict(TypedDict):
    id: str
    r"""Tax Config ID"""
    body: DtoTaxAssociationUpdateRequestTypedDict
    r"""Tax Config Request"""


class UpdateTaxAssociationRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Tax Config ID"""

    body: Annotated[
        DtoTaxAssociationUpdateRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Tax Config Request"""
