"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_updateaddonrequest import (
    DtoUpdateAddonRequest,
    DtoUpdateAddonRequestTypedDict,
)
from flexprice_temp.types import BaseModel
from flexprice_temp.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateAddonRequestTypedDict(TypedDict):
    id: str
    r"""Addon ID"""
    body: DtoUpdateAddonRequestTypedDict
    r"""Update Addon Request"""


class UpdateAddonRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Addon ID"""

    body: Annotated[
        DtoUpdateAddonRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Update Addon Request"""
